lang: fr
title: Régis GALLON
description: Maître de conférences (assistant professor) au Cnam/Intechmer
email: regis.gallon@lecnam.net
github:
  Enseignement: 
  Recherche: 
  Publication:
  G2Sd App: https://shiny.cnam.fr/G2Sd/

gems:
  - jekyll-seo-tag
google_analytics: true



theme: jekyll-theme-architect

