lang: fr
title: Régis GALLON
description: Maître de conférences (assistant professor) au Cnam/Intechmer
email: regis.gallon@lecnam.net

gems:
  - jekyll-seo-tag
google_analytics: true



theme: jekyll-theme-architect

